/**
 * 호텔 상세 페이지용 임시 데이터
 * TODO: 실제 API 연동 시 제거 예정
 */
export const getMockHotelData = (hotelId) => ({
  id: hotelId || 1,
  name: "신라스테이 광화문",
  rating: 8.4,
  reviewCount: 245,
  location: "서울 종로구 삼봉로 71",
  district: "종로구",
  description:
    "광화문 중심부에 위치한 프리미엄 비즈니스 호텔입니다. 모든 객실에서 서울의 아름다운 전망을 감상하실 수 있습니다.",
  checkInTime: "15:00",
  checkOutTime: "11:00",
  starRating: 4,
  amenities: [
    "무료 WiFi",
    "수영장",
    "피트니스 센터",
    "레스토랑",
    "주차장",
    "비즈니스 센터",
  ],
  images: [
    "/hotel-main.jpg",
    "/hotel-room.jpg",
    "/hotel-lobby.jpg",
    "/hotel-pool.jpg",
  ],
  rooms: [
    {
      id: 1,
      name: "스탠다드 더블",
      size: "27㎡",
      bedType: "더블",
      maxOccupancy: 2,
      price: 180000,
      originalPrice: 220000,
      discount: 18,
      amenities: ["무료 WiFi", "미니바", "금연", "욕조"],
      images: ["/room1.jpg", "/room1-2.jpg"],
      description: "편안한 휴식을 위한 기본형 객실입니다.",
      checkInInfo: "무료 취소 2024.10.19(일) 23:59 전까지",
    },
    {
      id: 2,
      name: "디럭스 트윈",
      size: "32㎡",
      bedType: "트윈",
      maxOccupancy: 2,
      price: 220000,
      originalPrice: 280000,
      discount: 21,
      amenities: ["무료 WiFi", "미니바", "금연", "욕조", "발코니"],
      images: ["/room2.jpg", "/room2-2.jpg"],
      description: "넓은 공간과 편안한 침대 2개가 제공되는 객실입니다.",
      checkInInfo: "무료 취소 2024.10.19(일) 23:59 전까지",
    },
    {
      id: 3,
      name: "이그제큐티브 스위트",
      size: "52㎡",
      bedType: "킹",
      maxOccupancy: 3,
      price: 380000,
      originalPrice: 450000,
      discount: 16,
      amenities: ["무료 WiFi", "미니바", "금연", "욕조", "거실", "네스프레소"],
      images: ["/room3.jpg", "/room3-2.jpg"],
      description: "거실과 침실이 분리된 프리미엄 객실입니다.",
      checkInInfo: "무료 취소 2024.10.19(일) 23:59 전까지",
    },
    {
      id: 4,
      name: "프리미엄 디럭스",
      size: "38㎡",
      bedType: "더블",
      maxOccupancy: 2,
      price: 280000,
      originalPrice: 340000,
      discount: 18,
      amenities: ["무료 WiFi", "미니바", "금연", "욕조", "시티뷰"],
      images: ["/room4.jpg", "/room4-2.jpg"],
      description: "도심 전망을 감상할 수 있는 프리미엄 객실입니다.",
      checkInInfo: "무료 취소 2024.10.19(일) 23:59 전까지",
    },
  ],
  reviews: [
    {
      id: 1,
      rating: 9.0,
      userName: "김**",
      date: "2024.10.10",
      roomType: "스탠다드 더블",
      comment:
        "위치도 좋고 깨끗해서 만족스러웠습니다. 직원분들도 친절하시고 조식도 훌륭했어요!",
    },
    {
      id: 2,
      rating: 8.5,
      userName: "이**",
      date: "2024.10.08",
      roomType: "디럭스 트윈",
      comment: "가족 여행으로 이용했는데 방이 넓고 편안했습니다.",
    },
    {
      id: 3,
      rating: 7.5,
      userName: "박**",
      date: "2024.10.05",
      roomType: "프리미엄 디럭스",
      comment: "전체적으로 좋았지만 가격대비 아쉬운 부분도 있었어요.",
    },
  ],
});
